#
# <https://github.com/KFERMercer/OpenWrt-CI>
#
# Copyright (C) 2019 P3TERX
#
# Copyright (C) 2020 KFERMercer
#
name: OpenWrt-CI
on:
  schedule:
    - cron: 0 20 * * *
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_openwrt:

    name: Build OpenWrt Firmware

    runs-on: ubuntu-latest

    steps:
      - name: Checkout OpenWrt
        id: checkout_OpenWrt
        uses: actions/checkout@v4
        with:
          repository: coolsnowwolf/lede
        # run: |
          # echo "repo_path=$(pwd)" >> $GITHUB_OUTPUT
          # echo "git_file_last_time=$(git log -1 --format=%cd)" >> $GITHUB_OUTPUT

      - name: Check for updates
        id: check
        run: |
          echo "$PWD"
          # 获取最新提交的时间
          git_time=$(git log -1 --format=%cd --date=iso)
          echo "Git time: $git_time"

          # 获取当前系统时间
          system_time=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "System time: $system_time"

          # 将时间转换为秒
          git_time_seconds=$(date -u -d "$git_time" +"%s")
          system_time_seconds=$(date -u -d "$system_time" +"%s")

          # 计算时差
          time_difference=$(expr $system_time_seconds - $git_time_seconds)
          echo "Time difference in seconds: $time_difference"