#
# <https://github.com/KFERMercer/OpenWrt-CI>
#
# Copyright (C) 2019 P3TERX
#
# Copyright (C) 2020 KFERMercer
#
name: OpenWrt-CI
on:
  schedule:
    - cron: 0 20 * * *
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_openwrt:

    name: Build OpenWrt Firmware

    runs-on: ubuntu-latest

    steps:
      - name: Checkout OpenWrt
        uses: actions/checkout@v4
        with:
          repository: coolsnowwolf/lede

      - name: Check for updates
        id: check
        run: |
          ls -al